# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkedBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_secilen = QtWidgets.QPushButton(self.centralwidget)
        self.btn_secilen.setGeometry(QtCore.QRect(330, 310, 151, 61))
        self.btn_secilen.setObjectName("btn_secilen")
        self.lbl_text = QtWidgets.QLabel(self.centralwidget)
        self.lbl_text.setGeometry(QtCore.QRect(290, 70, 241, 101))
        self.lbl_text.setText("")
        self.lbl_text.setObjectName("lbl_text")
        self.grouphobi = QtWidgets.QGroupBox(self.centralwidget)
        self.grouphobi.setGeometry(QtCore.QRect(20, 20, 211, 221))
        self.grouphobi.setObjectName("grouphobi")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.grouphobi)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 160, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_sinema = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cb_sinema.setAcceptDrops(False)
        self.cb_sinema.setObjectName("cb_sinema")
        self.verticalLayout.addWidget(self.cb_sinema)
        self.cb_kitap_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cb_kitap_2.setObjectName("cb_kitap_2")
        self.verticalLayout.addWidget(self.cb_kitap_2)
        self.cb_spor = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cb_spor.setObjectName("cb_spor")
        self.verticalLayout.addWidget(self.cb_spor)
        self.cb_bos = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cb_bos.setObjectName("cb_bos")
        self.verticalLayout.addWidget(self.cb_bos)
        self.groupders = QtWidgets.QGroupBox(self.centralwidget)
        self.groupders.setGeometry(QtCore.QRect(580, 30, 211, 221))
        self.groupders.setObjectName("groupders")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupders)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 20, 160, 181))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cb_sinema_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cb_sinema_2.setAcceptDrops(False)
        self.cb_sinema_2.setObjectName("cb_sinema_2")
        self.verticalLayout_2.addWidget(self.cb_sinema_2)
        self.cb_kitap_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cb_kitap_3.setObjectName("cb_kitap_3")
        self.verticalLayout_2.addWidget(self.cb_kitap_3)
        self.cb_spor_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cb_spor_2.setObjectName("cb_spor_2")
        self.verticalLayout_2.addWidget(self.cb_spor_2)
        self.cb_bos_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cb_bos_2.setObjectName("cb_bos_2")
        self.verticalLayout_2.addWidget(self.cb_bos_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_secilen.setText(_translate("MainWindow", "seçilenleri al"))
        self.grouphobi.setTitle(_translate("MainWindow", "GroupBox"))
        self.cb_sinema.setText(_translate("MainWindow", "sinema"))
        self.cb_kitap_2.setText(_translate("MainWindow", "kitap okuma"))
        self.cb_spor.setText(_translate("MainWindow", "spor "))
        self.cb_bos.setText(_translate("MainWindow", "bos"))
        self.groupders.setTitle(_translate("MainWindow", "GroupBox"))
        self.cb_sinema_2.setText(_translate("MainWindow", "web tasarım"))
        self.cb_kitap_3.setText(_translate("MainWindow", "python"))
        self.cb_spor_2.setText(_translate("MainWindow", "html"))
        self.cb_bos_2.setText(_translate("MainWindow", "secmeli"))
