# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gorsel_Arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(409, 346)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.irtifa = QtWidgets.QLabel(self.centralwidget)
        self.irtifa.setGeometry(QtCore.QRect(40, 70, 47, 13))
        self.irtifa.setObjectName("irtifa")
        self.hiz = QtWidgets.QLabel(self.centralwidget)
        self.hiz.setGeometry(QtCore.QRect(40, 180, 47, 13))
        self.hiz.setObjectName("hiz")
        self.batarya = QtWidgets.QLabel(self.centralwidget)
        self.batarya.setGeometry(QtCore.QRect(40, 240, 47, 13))
        self.batarya.setObjectName("batarya")
        self.pro_batarya = QtWidgets.QProgressBar(self.centralwidget)
        self.pro_batarya.setGeometry(QtCore.QRect(40, 260, 171, 20))
        self.pro_batarya.setProperty("value", 24)
        self.pro_batarya.setObjectName("pro_batarya")
        self.lcd_hiz = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_hiz.setGeometry(QtCore.QRect(40, 200, 101, 31))
        self.lcd_hiz.setObjectName("lcd_hiz")
        self.sistemi_baslat = QtWidgets.QPushButton(self.centralwidget)
        self.sistemi_baslat.setGeometry(QtCore.QRect(240, 20, 101, 41))
        self.sistemi_baslat.setObjectName("sistemi_baslat")
        self.sistemi_durdur = QtWidgets.QPushButton(self.centralwidget)
        self.sistemi_durdur.setGeometry(QtCore.QRect(240, 70, 101, 41))
        self.sistemi_durdur.setObjectName("sistemi_durdur")
        self.lbl_irtifa = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.lbl_irtifa.setGeometry(QtCore.QRect(40, 100, 104, 71))
        self.lbl_irtifa.setObjectName("lbl_irtifa")
        self.dron_adi = QtWidgets.QLabel(self.centralwidget)
        self.dron_adi.setGeometry(QtCore.QRect(280, 140, 61, 16))
        self.dron_adi.setObjectName("dron_adi")
        self.lbl_dronadi = QtWidgets.QLineEdit(self.centralwidget)
        self.lbl_dronadi.setGeometry(QtCore.QRect(250, 160, 113, 20))
        self.lbl_dronadi.setObjectName("lbl_dronadi")
        self.lbl_dronkilo = QtWidgets.QLineEdit(self.centralwidget)
        self.lbl_dronkilo.setGeometry(QtCore.QRect(250, 210, 113, 20))
        self.lbl_dronkilo.setObjectName("lbl_dronkilo")
        self.dron_kilo = QtWidgets.QLabel(self.centralwidget)
        self.dron_kilo.setGeometry(QtCore.QRect(270, 190, 71, 16))
        self.dron_kilo.setObjectName("dron_kilo")
        self.lbl_dronpil = QtWidgets.QLineEdit(self.centralwidget)
        self.lbl_dronpil.setGeometry(QtCore.QRect(250, 260, 113, 20))
        self.lbl_dronpil.setObjectName("lbl_dronpil")
        self.dron_pil = QtWidgets.QLabel(self.centralwidget)
        self.dron_pil.setGeometry(QtCore.QRect(280, 240, 47, 13))
        self.dron_pil.setObjectName("dron_pil")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 31, 31))
        self.label.setObjectName("label")
        self.l_dronid = QtWidgets.QLabel(self.centralwidget)
        self.l_dronid.setGeometry(QtCore.QRect(70, 30, 47, 13))
        self.l_dronid.setText("")
        self.l_dronid.setObjectName("l_dronid")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 409, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.irtifa.setText(_translate("MainWindow", "İrtifa (m)"))
        self.hiz.setText(_translate("MainWindow", "Hız (km/s)"))
        self.batarya.setText(_translate("MainWindow", "Batarya"))
        self.sistemi_baslat.setText(_translate("MainWindow", "Sistemi Başlat"))
        self.sistemi_durdur.setText(_translate("MainWindow", "Sistemi Durdur"))
        self.dron_adi.setText(_translate("MainWindow", "Dronun Adı"))
        self.dron_kilo.setText(_translate("MainWindow", "Dronun Kilosu"))
        self.dron_pil.setText(_translate("MainWindow", "Dronun Pil"))
        self.label.setText(_translate("MainWindow", "dron:"))
